### ISSUE TITLE
GDAL 2.0 integration

### ISSUE THREAD

**Issue by lucianpls** [nasa-gibs/mrf#13]
Even Roualt has done all the work for integration in GDAL 2.0, I've applied his patches one by one in the lp branch, with references to the GDAL trac, ticket 6342.

Most changes were cosmetic or minor, yet there were a couple of potential memory leaks and issues.

LERC format code is the most affected, because it made heavy use of unaligned memory reads/writes.  These are not an issue on Intel x86 and x64 CPUs and don't reduce performance on recent CPUs either.  But code checking tools warn/complain about the practice.
The expedient solution makes heavy use of memcpy, which probably reduces performance.  Maybe a better solution can be found

**Comment by rouault** [comment]
Regarding using memcpy(&aInt, ptr, sizeof(int)) instead of aInt = *(int*)ptr, optimizers generate the same code. See :

```
$ cat test.c
#include <string.h>

int foo(char* ptr)
{
    return *(int*)ptr;
}

int bar(char* ptr)
{
    int i;
    memcpy(&i, ptr, 4);
    return i;
}
```

```
$ gcc -O2 -c test.c
```

```
$ objdump -s test.o
Disassembly of section .text:

0000000000000000 <foo>:
   0:	8b 07                	mov    (%rdi),%eax
   2:	c3                   	retq   
   3:	66 66 66 66 2e 0f 1f 	nopw   %cs:0x0(%rax,%rax,1)
   a:	84 00 00 00 00 00 

0000000000000010 <bar>:
  10:	8b 07                	mov    (%rdi),%eax
  12:	c3                   	retq   
```

The use of memcpy() avoids gcc -fsanitize=undefined to complain at runtime about potential portability problems.

**Comment by tmaurer3** [comment]
I'd rather not call memcpy for each pixel: 
_ not every compiler may be as smart as gcc
_ the latest when you hit a system that only accepts an integer on a 4 byte aligned address Lerc will slow down to a crawl
_ not exactly the nicest looking code

Other options: 

_ 1)  Do the bit shifting into a byte array, not uint array. Tried it, works. Slow down depends on the bits per pixel packet size, the larger, the slower. Up to 50% slower decode observed. Theoretical worst case is 4x slower. 
_ 2)  Add a uint buffer to the BitStuffer class. Do the bit stuffing into that buffer, memcpy out to bit stream when done. Memcpy gets called once per micro block, not per pixel. Code looks clean. Slow down observed so far very little, single percent mostly. Worst seen 15% slower. Sometimes also faster. The single memcpy call per micro block cannot cost much cpu time compared to the rest of all the bit stuffing work. 

So I'm switching to option 2).  Best, Thomas.

**Comment by lucianpls** [comment]
MRF is fully integrated in the GDAL trunk.  This repository will be used mostly for development while the GDAL will be more stable and better tested.
