### ISSUE TITLE
MRF index size issue with z-dimension

### ISSUE THREAD

**Issue by jtroberts** [nasa-gibs/mrf#26]
An issue was found where the MRF index size apparently resets to 0 bytes.  Given a large 15m product, the z-size was set to 163 levels, and the index looks okay:
 
gdal_translate -of MRF -co COMPRESS=PNG -co BLOCKSIZE=512 -outsize 2621440 1310720 -co ZSIZE=163 -co NOCOPY=true -co UNIFORM_SCALE=2 test.tif test.mrf
test.idx  = 45578122592 bytes
 
When we try the product again with 164 levels, the index file gets created with 0 bytes:
 
gdal_translate -of MRF -co COMPRESS=PNG -co BLOCKSIZE=512 -outsize 2621440 1310720 -co ZSIZE=164 -co NOCOPY=true -co UNIFORM_SCALE=2 test.tif test.mrf
test.idx  = 0 bytes
 
If I reduce the outsize, I can increase the z-size proportionally.  However, the index appears to reach around 43GB before resetting to 0 bytes.

**Comment by lucianpls** [comment]
Indeed, the calculation of total page count per level is done on 32bit signed int, so it is limited to 2GB.  It comes out to a max of 32GB index size for base resolution, about 44GB for files with space for pyramids.

**Comment by lucianpls** [comment]
Fixed by https://github.com/nasa-gibs/mrf/commit/1e4ea1b773731334508ec2cd2fd1e7b6996f82c6
