### ISSUE TITLE
Broken when tyring to build on RHEL 7

### ISSUE THREAD

**Issue by k2patel** [nasa-gibs/mrf#31]
File  :  mrf/src/gdal_mrf/frmts/mrf/mrf_band.cpp
fatal error: ../zlib/zlib.h: No such file or directory
#include "../zlib/zlib.h" 

In order to fix i've to modify +#include "zlib.h"
OR 
You +#include <zlib.h>
either works.

**Comment by lucianpls** [comment]
Are you compiling it just by itself?
This source is meant to be compiled in a GDAL source folder, where the ../zlib does exist, regardless of the Linux distribution.

**Comment by k2patel** [comment]
No, I'm building gdal 2.1.0 ( which has inbuilt mrf )
that's my point is - it is referenced "../zlib/zlib.h" in the source file. rather than using system provide zlib.h in /usr/include ( may vary between OS ).

I've removed the local reference and ask to look for the system include.
Hope this make sense.

**Comment by lucianpls** [comment]
MRF currently depends on GDAL using the GDAL libjpeg and libpng, and GDAL libpng uses the internal zlib.  I know GDAL can use external versions of those libraries, but getting those configurations to work on all GDAL supported OSs takes a bit of work.
Are you disabling the internal zlib use intentionally?

**Comment by k2patel** [comment]
Well in order to use internal zlib it must exist while gdal source i do not
see it exist.

I can verify again, but it failed to compile on RHEL 7 and fedora 23.

Only way I can get it to build if I use the zlib provided with the OS.

The other option I see is to provide config option to choose between.

Will update you one I verify again.

Thanx

**Comment by lucianpls** [comment]
Which GDAL 2.1 source download did you use?
I checked, both in the released gdal210.zip and in the current GDAL 2.1 branch, the folder frmts/zlib and its content do exist.  Or maybe the folder or file access rights were wrong?

**Comment by k2patel** [comment]
i'm using http://download.osgeo.org/gdal/2.1.0/gdal-2.1.0.tar.gz
interesting enough that the i downloaded on July 1st it's missing zlib folder, today i've downloaded again to verify and i find the zlib folder exists.

Anyway, it seems this issue can be closed.

Thank you.
