### ISSUE TITLE
Internal mask support

### ISSUE THREAD

**Issue by lucianpls** [nasa-gibs/mrf#36]
MRF currently supports mask via PAM, as external files.  The external mask doesn't work through caching or cloning MRFs, it is ignored.
MRF should support a mask internal to the tile, at least for the JPEG compression format, which works through caching or cloning MRFs.

**Comment by lucianpls** [comment]
Added Zen mask mechanism

**Comment by lucianpls** [comment]
MRF with JPEG compression contain the Zen extension.  The extension has been tested and seems to function as designed.  See updated documentation.

**Comment by oysteinfs** [comment]
Hey! Im trying to create mrf cache with a rgb tiff file as source raster. The tiff file has internal masking with overviews and i cant seem to get the mrf to recognise the internal mask of the source raster. Any tips on how to create a mrf cache that works with internal masking?

**Comment by lucianpls** [comment]
@oysteinfs 
Mask in gdal is a different concept from normal bands, there are a few different ways it can be derived. I think the model itself comes from TIFF, where the mask can be separate from the bands. MRF only handles the mask as a normal band (like in RGBA), with the same datatype as the other bands, but not as a separate bitmask. This is a common feature on many other formats, I doubt that TIF can be easily converted to a different format. Adding ALL of the TIF features to MRF is not in scope, MRF is not a 100% compatible TIF.
If you really need to do this, you can either try to convert to a TIF where the mask is an explicit band, or use a VRT file that also converts the mask to band, then cache that VRT. I think it should be possible to embed the VRT itself into the caching MRF file, so it doesn't have to be a separate file. Either way it's not very efficient. If you share a sample file I can take a look and let you know what I find out.
I would also like to know more details about the context of your use of caching MRFs. Let's move this discussion on regular email!

**Comment by oysteinfs** [comment]
@lucianpls 
Thanks for the quick reply! I've sent you an email with more details. I can probably produce some data to test with :)
