### ISSUE TITLE
Internal resampling algorithms

### ISSUE THREAD

**Issue by lucianpls** [nasa-gibs/mrf#46]
MRF has two internal overview resampling modes, one based on averaging and one based on nearest neighbor, both implemented only for overview factor of 2.
There are at least two problems with the current state:
- The code does not check that the factor is indeed 2.  This has led to the gdal unit testing the internal modes with a factor of 3.  Which works, but produces bad results.  It passes the numeric test, but the result is not valid.
- The name for the nearest neighbor resampling mode is badly chosen.  GDAL accepts any name that starts with "near" as it's version.  The MRF tests first, and currently uses the same test, so the user can't really tell which algorithm is used.

Proposed solution:
- Rename the nearest neighbor resampling to "nnb".  This will break backwards compatibility, some scripts and potentially some codes will need to change.
- Reject unsupported overview scaling factors.  This will not cause serious disruptions, as the result would have been wrong anyhow.

**Comment by mcechini** [comment]
I prefer the backwards compatible option where unsupported overview scaling factors are rejected.

**Comment by lucianpls** [comment]
It's not a choice unfortunately, sorry.  Those are two separate changes, to remedy the current situation.
It's not much of a change, but some of the GIBS scripts will have to be updated when this change is adopted.

**Comment by lucianpls** [comment]
Fixed in gdal trunk
